nodeLinker: "pnpm"
pnpMode: "strict"

packageExtensions:
  react-scripts@*:
    dependencies:
      sass-loader: "*"
    peerDependencies:
      sass: "*"
  bootstrap@*:
    dependencies:
      postcss-flexbugs-fixes: "*"
    peerDependencies:
      postcss-flexbugs-fixes: "*"
