{
 "title": "Dappmanager-custom-metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Ethereum Client Local",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_eth_client_target_local{ethClientTargetLocal=\"local\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "Ethereum Client Local (on / off)"
    }
   ]
  },
  {
   "title": "Ethereum fallback",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_eth_fallback_enabled{ethFallbackEnabled=\"enabled\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "Ethereum fallback (on / off)"
    }
   ]
  },
  {
   "title": "IPFS Gateways",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_ipfs_gateway_count{instance=\"dappmanager.dappnode:80\",gatewayCount=\"count\"}",
     "legendFormat": "IPFS Gateways Configured"
    }
   ]
  },
  {
   "title": "System packages auto-updates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_auto_updates_system_packages{autoUpdatesSystemPackages=\"enabled\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "System packages auto-updates (on / off)"
    }
   ]
  },
  {
   "title": "User packages auto-updates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_auto_updates_user_packages{autoUpdatesUserPackages=\"enabled\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "User packages auto-updates (on / off)"
    }
   ]
  },
  {
   "title": "Views UI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "dappmanager_views{instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "Views UI (requests)"
    }
   ]
  },
  {
   "title": "CPU temperature (main and max)",
   "type": "timeseries",
   "description": "Average and max CPU temperatures in ºC",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "dappmanager_cpu_temperature_celsius{type=\"max\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dappmanager_cpu_temperature_celsius{type=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EXECUTION CLIENT MAINNET",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_staker_config{executionClient=\"mainnet\",instance=\"dappmanager.dappnode:80\"}"
    }
   ]
  },
  {
   "title": "CONSENSUS CLIENT MAINNET",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_staker_config{consensusClient=\"mainnet\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "Consensus client Prysm"
    }
   ]
  },
  {
   "title": "EXECUTION CLIENT GNOSIS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_staker_config{executionClient=\"gnosis\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "Execution client nethermind"
    }
   ]
  },
  {
   "title": "CONSENSUS CLIENT GNOSIS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dappmanager_staker_config{consensusClient=\"gnosis\",instance=\"dappmanager.dappnode:80\"}",
     "legendFormat": "Consensus client Prysm"
    }
   ]
  }
 ]
}