ARG NODE_VERSION=20.3.0

# Common base so it's cached
# --platform=$BUILDPLATFORM is used build javascript source with host arch
# Otherwise webpack builds on emulated archs can be extremely slow (+1h)
ARG BASE_IMAGE=node:${NODE_VERSION}-alpine

# Initial stage to gather git data
FROM --platform=${BUILDPLATFORM:-amd64} ${BASE_IMAGE} AS git-data
WORKDIR /usr/src/app
RUN apk add --no-cache git python3 py3-pip build-base
COPY .git dappnode_package.json docker/getGitData.js ./
RUN node getGitData /usr/src/app/.git-data.json


# Build + Prod stage
FROM node:${NODE_VERSION}-alpine
ENV COMPOSE_HTTP_TIMEOUT=300 \
  DOCKER_CLIENT_TIMEOUT=300 \
  DOCKER_HOST=unix:///var/run/docker.sock \
  UI_FILES_PATH=/app/packages/admin-ui/build \
  GIT_DATA_PATH=.git-data.json \
  TEST=true \
  VITE_APP_API_URL=http://my.dappnode:5000/
WORKDIR /app
RUN apk update && apk add --no-cache docker curl docker-cli-compose xz zip unzip libltdl bash git bind bind-tools bind-dev \ 
  miniupnpc dbus tmux avahi-tools

# Copy git data
COPY --from=git-data /usr/src/app/.git-data.json $GIT_DATA_PATH

COPY docker/start_dev.sh /usr/src/app/start_dev.sh

# Build the src code:
# Copy and install deps first to cache
COPY package.json yarn.lock tsconfig.json ./
COPY packages packages

RUN yarn --immutable --non-interactive --ignore-optional

ENV VITE_APP_API_URL /
RUN yarn build

ENTRYPOINT [ "/usr/src/app/start_dev.sh" ]