/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ACLOracle,
  ACLOracleInterface,
} from "../../contracts_v0.4/ACLOracle";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "who",
        type: "address",
      },
      {
        name: "where",
        type: "address",
      },
      {
        name: "what",
        type: "bytes32",
      },
    ],
    name: "canPerform",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ACLOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ACLOracleInterface {
    return new Interface(_abi) as ACLOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ACLOracle {
    return new Contract(address, _abi, runner) as unknown as ACLOracle;
  }
}
