/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  APMRegistryConstants,
  APMRegistryConstantsInterface,
} from "../../contracts_v0.4/APMRegistryConstants";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "REPO_APP_NAME",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "APM_APP_NAME",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "ENS_SUB_APP_NAME",
    outputs: [
      {
        name: "",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6060604052341561000f57600080fd5b6101dc8061001e6000396000f3006060604052600436106100565763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663023d6c03811461005b5780631219d5c8146100e5578063231cb6ab146100f8575b600080fd5b341561006657600080fd5b61006e61010b565b60405160208082528190810183818151815260200191508051906020019080838360005b838110156100aa578082015183820152602001610092565b50505050905090810190601f1680156100d75780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34156100f057600080fd5b61006e610142565b341561010357600080fd5b61006e610179565b60408051908101604052600881527f61706d2d7265706f000000000000000000000000000000000000000000000000602082015281565b60408051908101604052600c81527f61706d2d72656769737472790000000000000000000000000000000000000000602082015281565b60408051908101604052600a81527f61706d2d656e73737562000000000000000000000000000000000000000000006020820152815600a165627a7a723058205036f68f134cfe83bc8d09e7b2ae2656ea7732093f7a7bc7b6301c442e4cfa3a0029";

type APMRegistryConstantsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: APMRegistryConstantsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class APMRegistryConstants__factory extends ContractFactory {
  constructor(...args: APMRegistryConstantsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      APMRegistryConstants & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): APMRegistryConstants__factory {
    return super.connect(runner) as APMRegistryConstants__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): APMRegistryConstantsInterface {
    return new Interface(_abi) as APMRegistryConstantsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): APMRegistryConstants {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as APMRegistryConstants;
  }
}
