/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { ethers } from "ethers";
import type { ContractRunner } from "ethers";
import type { IACL, IACLInterface } from "../../contracts_v0.4/IACL.js";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "permissionsCreator",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "who",
        type: "address",
      },
      {
        name: "where",
        type: "address",
      },
      {
        name: "what",
        type: "bytes32",
      },
      {
        name: "how",
        type: "bytes",
      },
    ],
    name: "hasPermission",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IACL__factory {
  static readonly abi = _abi;
  static createInterface(): IACLInterface {
    return new ethers.Interface(_abi) as IACLInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IACL {
    return new ethers.Contract(address, _abi, runner) as unknown as IACL;
  }
}
