/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { ethers } from "ethers";
import type { ContractRunner } from "ethers";
import type {
  IAppProxy,
  IAppProxyInterface,
} from "../../contracts_v0.4/IAppProxy.js";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "isUpgradeable",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getCode",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAppProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IAppProxyInterface {
    return new ethers.Interface(_abi) as IAppProxyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAppProxy {
    return new ethers.Contract(address, _abi, runner) as unknown as IAppProxy;
  }
}
