/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEVMScriptRegistry,
  IEVMScriptRegistryInterface,
} from "../../contracts_v0.4/IEVMScriptRegistry";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "executor",
        type: "address",
      },
    ],
    name: "addScriptExecutor",
    outputs: [
      {
        name: "id",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "executorId",
        type: "uint256",
      },
    ],
    name: "disableScriptExecutor",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "script",
        type: "bytes",
      },
    ],
    name: "getScriptExecutor",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEVMScriptRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IEVMScriptRegistryInterface {
    return new Interface(_abi) as IEVMScriptRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEVMScriptRegistry {
    return new Contract(address, _abi, runner) as unknown as IEVMScriptRegistry;
  }
}
