/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common.js";

export interface DeployDelegateScriptInterface extends Interface {
  getFunction(nameOrSignature: "execScript"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execScript",
    values: [BytesLike, BytesLike, AddressLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "execScript", data: BytesLike): Result;
}

export interface DeployDelegateScript extends BaseContract {
  connect(runner?: ContractRunner | null): DeployDelegateScript;
  waitForDeployment(): Promise<this>;

  interface: DeployDelegateScriptInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  /**
   * Executes script by delegatecall into a deployed contract (exec() function)
   * @param _blacklist If any address is passed, will revert.
   * @param _input ABI encoded call to be made to contract (if empty executes default exec() function)
   * @param _script [ specId (uint32) ][ contractInitcode (bytecode) ]
   * @returns Call return data
   */
  execScript: TypedContractMethod<
    [_script: BytesLike, _input: BytesLike, _blacklist: AddressLike[]],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execScript"
  ): TypedContractMethod<
    [_script: BytesLike, _input: BytesLike, _blacklist: AddressLike[]],
    [string],
    "nonpayable"
  >;

  filters: {};
}
