/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common.js";

export interface IEVMScriptRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addScriptExecutor"
      | "disableScriptExecutor"
      | "getScriptExecutor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addScriptExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disableScriptExecutor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScriptExecutor",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addScriptExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableScriptExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScriptExecutor",
    data: BytesLike
  ): Result;
}

export interface IEVMScriptRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IEVMScriptRegistry;
  waitForDeployment(): Promise<this>;

  interface: IEVMScriptRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addScriptExecutor: TypedContractMethod<
    [executor: AddressLike],
    [bigint],
    "nonpayable"
  >;

  disableScriptExecutor: TypedContractMethod<
    [executorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getScriptExecutor: TypedContractMethod<[script: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addScriptExecutor"
  ): TypedContractMethod<[executor: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "disableScriptExecutor"
  ): TypedContractMethod<[executorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getScriptExecutor"
  ): TypedContractMethod<[script: BytesLike], [string], "view">;

  filters: {};
}
