/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common.js";

export interface KernelConstantsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "KERNEL_APP_ID"
      | "APP_ADDR_NAMESPACE"
      | "KERNEL_APP"
      | "CORE_NAMESPACE"
      | "ACL_APP"
      | "ACL_APP_ID"
      | "APP_BASES_NAMESPACE"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "KERNEL_APP_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "APP_ADDR_NAMESPACE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KERNEL_APP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CORE_NAMESPACE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ACL_APP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ACL_APP_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "APP_BASES_NAMESPACE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "KERNEL_APP_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "APP_ADDR_NAMESPACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KERNEL_APP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CORE_NAMESPACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ACL_APP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ACL_APP_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "APP_BASES_NAMESPACE",
    data: BytesLike
  ): Result;
}

export interface KernelConstants extends BaseContract {
  connect(runner?: ContractRunner | null): KernelConstants;
  waitForDeployment(): Promise<this>;

  interface: KernelConstantsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  KERNEL_APP_ID: TypedContractMethod<[], [string], "view">;

  APP_ADDR_NAMESPACE: TypedContractMethod<[], [string], "view">;

  KERNEL_APP: TypedContractMethod<[], [string], "view">;

  CORE_NAMESPACE: TypedContractMethod<[], [string], "view">;

  ACL_APP: TypedContractMethod<[], [string], "view">;

  ACL_APP_ID: TypedContractMethod<[], [string], "view">;

  APP_BASES_NAMESPACE: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "KERNEL_APP_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "APP_ADDR_NAMESPACE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KERNEL_APP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CORE_NAMESPACE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACL_APP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ACL_APP_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "APP_BASES_NAMESPACE"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
