/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common.js";

export interface ScriptHelpersInterface extends Interface {
  getFunction(nameOrSignature: "abiEncode" | "memcpy"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "abiEncode",
    values: [BytesLike, BytesLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "memcpy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "abiEncode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "memcpy", data: BytesLike): Result;
}

export interface ScriptHelpers extends BaseContract {
  connect(runner?: ContractRunner | null): ScriptHelpers;
  waitForDeployment(): Promise<this>;

  interface: ScriptHelpersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abiEncode: TypedContractMethod<
    [_a: BytesLike, _b: BytesLike, _c: AddressLike[]],
    [string],
    "view"
  >;

  memcpy: TypedContractMethod<
    [_dest: BigNumberish, _src: BigNumberish, _len: BigNumberish],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abiEncode"
  ): TypedContractMethod<
    [_a: BytesLike, _b: BytesLike, _c: AddressLike[]],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "memcpy"
  ): TypedContractMethod<
    [_dest: BigNumberish, _src: BigNumberish, _len: BigNumberish],
    [void],
    "view"
  >;

  filters: {};
}
