/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as contractsV04 from "./contracts_v0.4/index.js";
export * as contractsV05 from "./contracts_v0.5/index.js";
