version: "3.5"
services:
  my-package:
    image: "my-package.dnp.dappnode.eth:0.1.0"
    build:
      context: .
    restart: unless-stopped
    volumes:
      - "data:/data"
    ports:
      - "8080"
    environment:
      EXTRA_OPTS: ""
volumes:
  data: {}
