/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common.js";

export interface EscapableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "changeOwnership"
      | "escapeHatchCaller"
      | "escapeHatchDestination"
      | "newOwnerCandidate"
      | "owner"
      | "proposeOwnership"
      | "removeOwnership"
      | "isTokenEscapable"
      | "escapeHatch"
      | "changeHatchEscapeCaller"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscapeHatchBlackistedToken"
      | "EscapeHatchCalled"
      | "OwnershipRemoved"
      | "OwnershipRequested"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escapeHatchCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escapeHatchDestination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newOwnerCandidate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenEscapable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escapeHatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeHatchEscapeCaller",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escapeHatchCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escapeHatchDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newOwnerCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenEscapable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escapeHatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeHatchEscapeCaller",
    data: BytesLike
  ): Result;
}

export namespace EscapeHatchBlackistedTokenEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscapeHatchCalledEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipRemovedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipRequestedEvent {
  export type InputTuple = [by: AddressLike, to: AddressLike];
  export type OutputTuple = [by: string, to: string];
  export interface OutputObject {
    by: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escapable extends BaseContract {
  connect(runner?: ContractRunner | null): Escapable;
  waitForDeployment(): Promise<this>;

  interface: EscapableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  /**
   * Can only be called by the `newOwnerCandidate`, accepts the  transfer of ownership
   */
  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  /**
   * In this 2nd option for ownership transfer `changeOwnership()` can  be called and it will immediately assign ownership to the `newOwner`
   * `owner` can step down and assign some other address to this role
   * @param _newOwner The address of the new owner
   */
  changeOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  escapeHatchCaller: TypedContractMethod<[], [string], "view">;

  escapeHatchDestination: TypedContractMethod<[], [string], "view">;

  newOwnerCandidate: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  /**
   * In this 1st option for ownership transfer `proposeOwnership()` must  be called first by the current `owner` then `acceptOwnership()` must be  called by the `newOwnerCandidate`
   * `onlyOwner` Proposes to transfer control of the contract to a  new owner
   * @param _newOwnerCandidate The address being proposed as the new owner
   */
  proposeOwnership: TypedContractMethod<
    [_newOwnerCandidate: AddressLike],
    [void],
    "nonpayable"
  >;

  /**
   * In this 3rd option for ownership transfer `removeOwnership()` can  be called and it will immediately assign ownership to the 0x0 address;  it requires a 0xdece be input as a parameter to prevent accidental use
   * Decentralizes the contract, this operation cannot be undone
   * @param _dac `0xdac` has to be entered for this function to work
   */
  removeOwnership: TypedContractMethod<
    [_dac: AddressLike],
    [void],
    "nonpayable"
  >;

  /**
   * Checks to see if `_token` is in the blacklist of tokens
   * @param _token the token address being queried
   * @returns False if `_token` is in the blacklist and can't be taken out of  the contract via the `escapeHatch()`
   */
  isTokenEscapable: TypedContractMethod<
    [_token: AddressLike],
    [boolean],
    "view"
  >;

  /**
   * The `escapeHatch()` should only be called as a last resort if a security issue is uncovered or something unexpected happened
   * @param _token to transfer, use 0x0 for ether
   */
  escapeHatch: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  /**
   * Changes the address assigned to call `escapeHatch()`
   * @param _newEscapeHatchCaller The address of a trusted account or  contract to call `escapeHatch()` to send the value in this contract to  the `escapeHatchDestination`; it would be ideal that `escapeHatchCaller`  cannot move funds out of `escapeHatchDestination`
   */
  changeHatchEscapeCaller: TypedContractMethod<
    [_newEscapeHatchCaller: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escapeHatchCaller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escapeHatchDestination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "newOwnerCandidate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeOwnership"
  ): TypedContractMethod<
    [_newOwnerCandidate: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOwnership"
  ): TypedContractMethod<[_dac: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isTokenEscapable"
  ): TypedContractMethod<[_token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "escapeHatch"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeHatchEscapeCaller"
  ): TypedContractMethod<
    [_newEscapeHatchCaller: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EscapeHatchBlackistedToken"
  ): TypedContractEvent<
    EscapeHatchBlackistedTokenEvent.InputTuple,
    EscapeHatchBlackistedTokenEvent.OutputTuple,
    EscapeHatchBlackistedTokenEvent.OutputObject
  >;
  getEvent(
    key: "EscapeHatchCalled"
  ): TypedContractEvent<
    EscapeHatchCalledEvent.InputTuple,
    EscapeHatchCalledEvent.OutputTuple,
    EscapeHatchCalledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipRemoved"
  ): TypedContractEvent<
    OwnershipRemovedEvent.InputTuple,
    OwnershipRemovedEvent.OutputTuple,
    OwnershipRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipRequested"
  ): TypedContractEvent<
    OwnershipRequestedEvent.InputTuple,
    OwnershipRequestedEvent.OutputTuple,
    OwnershipRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "EscapeHatchBlackistedToken(address)": TypedContractEvent<
      EscapeHatchBlackistedTokenEvent.InputTuple,
      EscapeHatchBlackistedTokenEvent.OutputTuple,
      EscapeHatchBlackistedTokenEvent.OutputObject
    >;
    EscapeHatchBlackistedToken: TypedContractEvent<
      EscapeHatchBlackistedTokenEvent.InputTuple,
      EscapeHatchBlackistedTokenEvent.OutputTuple,
      EscapeHatchBlackistedTokenEvent.OutputObject
    >;

    "EscapeHatchCalled(address,uint256)": TypedContractEvent<
      EscapeHatchCalledEvent.InputTuple,
      EscapeHatchCalledEvent.OutputTuple,
      EscapeHatchCalledEvent.OutputObject
    >;
    EscapeHatchCalled: TypedContractEvent<
      EscapeHatchCalledEvent.InputTuple,
      EscapeHatchCalledEvent.OutputTuple,
      EscapeHatchCalledEvent.OutputObject
    >;

    "OwnershipRemoved()": TypedContractEvent<
      OwnershipRemovedEvent.InputTuple,
      OwnershipRemovedEvent.OutputTuple,
      OwnershipRemovedEvent.OutputObject
    >;
    OwnershipRemoved: TypedContractEvent<
      OwnershipRemovedEvent.InputTuple,
      OwnershipRemovedEvent.OutputTuple,
      OwnershipRemovedEvent.OutputObject
    >;

    "OwnershipRequested(address,address)": TypedContractEvent<
      OwnershipRequestedEvent.InputTuple,
      OwnershipRequestedEvent.OutputTuple,
      OwnershipRequestedEvent.OutputObject
    >;
    OwnershipRequested: TypedContractEvent<
      OwnershipRequestedEvent.InputTuple,
      OwnershipRequestedEvent.OutputTuple,
      OwnershipRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
