on:
  release:
    types: [created, edited]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Trigger DNP_CORE build
    steps:
      - name: Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: dappnode/DNP_CORE
          event-type: build_release
